### ISSUE TITLE
Add Quantity.zero helper

### ISSUE THREAD

**Issue by skovmand** [wise-home/quantity#12]
I often need to default to a zero value in a calculation, for example: 

```
payments =
  case payments do
    [] -> Quantity.new(Decimal.new("0"), other_quantity.unit)
    payments -> Quantity.sum!(payments)
  end
```

A factory function for creating a quantity with the value 0 and a unit could change this to:

```
payments =
  case payments do
    [] -> Quantity.zero(other_quantity)
    payments -> Quantity.sum!(payments)
  end
```

Thoughts about naming:
- `Quantity.zero/1` is short and nice, but maybe a bit unclear
- `Quantity.new/1` would be possible too

@lasseebert What do you think?

**Comment by lasseebert** [comment]
@skovmand: I agree. Perhaps use `to_zero/1` for more clarity of what the function does?

**Comment by skovmand** [comment]
@lasseebert Good name :+1:
